-- Table: public.api_keys

-- DROP TABLE IF EXISTS public.api_keys;

CREATE TABLE IF NOT EXISTS public.api_keys
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    api_key character varying(255) COLLATE pg_catalog."default" NOT NULL,
    plano character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'basico'::character varying,
    limite integer NOT NULL,
    consumo integer NOT NULL DEFAULT 0,
    criado_em timestamp without time zone DEFAULT now(),
    dia date,
    CONSTRAINT api_keys_pkey PRIMARY KEY (id),
    CONSTRAINT api_keys_api_key_key UNIQUE (api_key)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.api_keys
    OWNER to postgres;