-- Table: public.recomendacoes

-- DROP TABLE IF EXISTS public.recomendacoes;

CREATE TABLE IF NOT EXISTS public.recomendacoes
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    destino character varying(255) COLLATE pg_catalog."default" NOT NULL,
    preco_passagem numeric(10,2) NOT NULL,
    data_ida date NOT NULL,
    data_volta date NOT NULL,
    imagem_ref text COLLATE pg_catalog."default" NOT NULL,
    criado_em timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT recomendacoes_pkey PRIMARY KEY (id),
    CONSTRAINT recomendacoes_preco_ck CHECK (preco_passagem >= 0::numeric),
    CONSTRAINT recomendacoes_datas_ck CHECK (data_volta >= data_ida)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.recomendacoes
    OWNER to postgres;
-- Index: recomendacoes_data_ida_idx

-- DROP INDEX IF EXISTS public.recomendacoes_data_ida_idx;

CREATE INDEX IF NOT EXISTS recomendacoes_data_ida_idx
    ON public.recomendacoes USING btree
    (data_ida ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: recomendacoes_destino_idx

-- DROP INDEX IF EXISTS public.recomendacoes_destino_idx;

CREATE INDEX IF NOT EXISTS recomendacoes_destino_idx
    ON public.recomendacoes USING btree
    (destino COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;