-- Table: public.users

-- DROP TABLE IF EXISTS public.users;

CREATE TABLE IF NOT EXISTS public.users
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nome text COLLATE pg_catalog."default" NOT NULL,
    api_token text COLLATE pg_catalog."default" NOT NULL DEFAULT (gen_random_uuid())::text,
    role text COLLATE pg_catalog."default" NOT NULL DEFAULT 'user'::text,
    criado_em timestamp with time zone NOT NULL DEFAULT now(),
    ativo boolean NOT NULL DEFAULT true,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_role_check CHECK (role = ANY (ARRAY['adm'::text, 'user'::text]))
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.users
    OWNER to postgres;
-- Index: users_api_token_uq

-- DROP INDEX IF EXISTS public.users_api_token_uq;

CREATE UNIQUE INDEX IF NOT EXISTS users_api_token_uq
    ON public.users USING btree
    (api_token COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;