-- Table: public.viagens

-- DROP TABLE IF EXISTS public.viagens;

CREATE TABLE IF NOT EXISTS public.viagens
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    destino character varying(255) COLLATE pg_catalog."default" NOT NULL,
    caracteristica character varying(255) COLLATE pg_catalog."default" NOT NULL,
    comprador character varying(255) COLLATE pg_catalog."default" NOT NULL,
    data_ida date NOT NULL,
    data_volta date NOT NULL,
    user_id bigint,
    CONSTRAINT viagens_pkey PRIMARY KEY (id),
    CONSTRAINT viagens_user_fk FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE SET NULL,
    CONSTRAINT chk_datas_viagem CHECK (data_volta >= data_ida)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.viagens
    OWNER to postgres;
-- Index: viagens_user_id_idx

-- DROP INDEX IF EXISTS public.viagens_user_id_idx;

CREATE INDEX IF NOT EXISTS viagens_user_id_idx
    ON public.viagens USING btree
    (user_id ASC NULLS LAST)
    TABLESPACE pg_default;